### ISSUE TITLE
Conditional Pipeline Job steps Azure ML v2

### ISSUE THREAD

**Issue by tommyJimmy87** [Azure/azureml-examples#1469]
## What example? Describe it

How to run steps conditionally from a Job pipeline (yaml) if possible at all.

Example: 
I want to run a step (fine-tuning for example) only on some boolean condition and I would like to pass this condition inside the yaml file which describe the pipeline Job. ( In Kubeflow this is possible through dsl.condition in the python sdk )

``` 
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: exp
description: description

jobs:
  #Training step
  train:
    name: training
    display_name: Model-training
    environment: azureml:ccep_train_env_docker@latest
    code: ../../training
    command: >-
      python train_aml.py
**IF <some condition>:**
  #Fine tune step
  finetuning:
    name: fine_tuning
    display_name: Fine-Tuning-Model
    code: ../../finetuning
    command: >-
      python finetune_aml.py


```
Not sure this is possible at all, in case would be great to have an ehnancement, is super useful.

Thanks

-
