### ISSUE TITLE
Example "1c_e2e_inline_components" fails with "Invalid output binding string".

### ISSUE THREAD

**Issue by PeterFogh** [Azure/azureml-examples#660]
## Which example? Describe the issue

example: 1c_e2e_inline_components
description: creating the pipeline job failes as all outputs has the error "Invalid output binding string".

## Additional context

How to reproduce the problem:
```
(base) fogh@ubuntuVM:~/work/open_source$ rm -rf azureml-previews/
(base) fogh@ubuntuVM:~/work/open_source$ git clone https://github.com/Azure/azureml-previews.git
Cloning into 'azureml-previews'...
remote: Enumerating objects: 8245, done.
remote: Counting objects: 100% (907/907), done.
remote: Compressing objects: 100% (337/337), done.
remote: Total 8245 (delta 601), reused 796 (delta 531), pack-reused 7338
Receiving objects: 100% (8245/8245), 25.38 MiB | 21.64 MiB/s, done.
Resolving deltas: 100% (4852/4852), done.
(base) fogh@ubuntuVM:~/work/open_source$ cd azureml-previews/previews/pipelines/samples/1c_e2e_inline_components/
(base) fogh@ubuntuVM:~/work/open_source/azureml-previews/previews/pipelines/samples/1c_e2e_inline_components$ git rev-parse HEAD
bb46163611bf31c568fc090ee4984bce1abe0ca9
(base) fogh@ubuntuVM:~/work/open_source/azureml-previews/previews/pipelines/samples/1c_e2e_inline_components$ az version
{
  "azure-cli": "2.27.0",
  "azure-cli-core": "2.27.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.0.1a4"
  }
}
(base) fogh@ubuntuVM:~/work/open_source/azureml-previews/previews/pipelines/samples/1c_e2e_inline_components$ az configure

Welcome to the Azure CLI! This command will guide you through logging in and setting some default values.

Your settings can be found at /home/fogh/.azure/config
Your current configuration is as follows:

[cloud]
name = AzureCloud

[core]
first_run = yes
output = json
collect_telemetry = no
cache_ttl = 10

[defaults]
group = oek-automatedaccounting-dev-rg
workspace = automatedaccounting-preview-mlsw

[logging]
enable_log_file = yes

Environment variables:
AZURE_ML_CLI_PRIVATE_FEATURES_ENABLED = true

Do you wish to change your settings? (y/N): N

You're all set! Here are some commands to try:
 $ az login
 $ az vm create --help
 $ az feedback

(base) fogh@ubuntuVM:~/work/open_source/azureml-previews/previews/pipelines/samples/1c_e2e_inline_components$ az ml job create --file pipeline.yml --set defaults.component_job.compute.target=azureml:DS12-v2
Command group 'ml job' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Validation for PipelineJobSchema failed:

 {
  "jobs": {
    "train-job": {
      "value": {
        "outputs": {
          "model_output": {
            "value": [
              {
                "_schema": [
                  "Invalid output binding string 'outputs.pipeline_job_trained_model' passed"
                ]
              },
              {
                "_schema": [
                  "Invalid input type."
                ]
              }
            ]
          }
        }
      }
    },
    "score-job": {
      "value": {
        "outputs": {
          "score_output": {
            "value": [
              {
                "_schema": [
                  "Invalid output binding string 'outputs.pipeline_job_scored_data' passed"
                ]
              },
              {
                "_schema": [
                  "Invalid input type."
                ]
              }
            ]
          }
        }
      }
    },
    "evaluate-job": {
      "value": {
        "outputs": {
          "eval_output": {
            "value": [
              {
                "_schema": [
                  "Invalid output binding string 'outputs.pipeline_job_evaluation_report' passed"
                ]
              },
              {
                "_schema": [
                  "Invalid input type."
                ]
              }
            ]
          }
        }
      }
    }
  }
} 

 If the job type is incorrect, change the 'type' property.
```

**Comment by PeterFogh** [comment]
Dfter downgrading to `az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2-public/ml-2.0.1a2-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2-public -y` the pipeline job could be created, however, it fails immediately by "train: error: argument --max_epocs: invalid int value: '{inputs.max_epocs}'"

**Comment by PeterFogh** [comment]
I found a solution thanks to @ManojBableshwar.
The YAML syntax for reference to other YAML attribute had changed such that all of the example did not work. The fix is to add ``  --${{ATTRIBUTE}} `` around each attribute.

For "1c_e2e_inline_components" needs to be changed to:
```
name: Train_score_eval_pipeline_job
type: pipeline_job

inputs:
  pipeline_job_training_input: #using dataset, can use datastore + datapath also
    data: 
      local_path: ./data
  pipeline_job_test_input:
    data:
      local_path: ./data
  pipeline_job_training_max_epocs: 20
  pipeline_job_training_learning_rate: 1.8
  pipeline_job_learning_rate_schedule: 'time-based'

outputs: 
  pipeline_job_trained_model:
    data: 
      path: /trained-model
  pipeline_job_scored_data:
    data: 
      path: /scored_data
  pipeline_job_evaluation_report:
    data: 
      path: /report

defaults:
  component_job:
    datastore: azureml:workspaceblobstore
    compute:
      target: ManojCluster

jobs:
  train-job:
    type: component_job
    component: 
      name: Train
      display_name: Train
      version: 10
      type: command_component
      inputs:
        training_data: 
          type: path
        max_epocs:
          type: integer
        learning_rate: 
          type: number
          default: 0.01
        learning_rate_schedule: 
          type: string
          default: time-based 
      outputs:
        model_output:
          type: path
      code:
        local_path: ./train_src
      environment: azureml:AzureML-Minimal:1
      command: >-
        python train.py 
        --training_data ${{inputs.training_data}}
        --max_epocs ${{inputs.max_epocs}}
        --learning_rate ${{inputs.learning_rate}}
        --learning_rate_schedule ${{inputs.learning_rate_schedule}}
        --model_output ${{outputs.model_output}}

    inputs:
      training_data: ${{inputs.pipeline_job_training_input}}
      max_epocs: ${{inputs.pipeline_job_training_max_epocs}}
      learning_rate: ${{inputs.pipeline_job_training_learning_rate}}
      learning_rate_schedule: ${{inputs.pipeline_job_learning_rate_schedule}}
    outputs:
      model_output: ${{outputs.pipeline_job_trained_model}}
  
  score-job:
    type: component_job
    component: 
      name: Score
      version: 10
      display_name: Score
      type: command_component
      inputs:
        model_input:
          type: path
        test_data:
          type: path
      outputs:
        score_output:
          type: path
      environment: azureml:AzureML-Minimal:1
      code:
        local_path: ./score_src
      command: >-
        python score.py 
        --model_input ${{inputs.model_input}}
        --test_data ${{inputs.test_data}}
        --score_output ${{outputs.score_output}}

    inputs:
      model_input: ${{jobs.train-job.outputs.model_output}}
      test_data: ${{inputs.pipeline_job_test_input}}
    outputs:
      score_output: ${{outputs.pipeline_job_scored_data}}

  evaluate-job:
    type: component_job
    component: 
      name: Eval
      version: 10
      display_name: Eval
      type: command_component
      inputs:
        scoring_result:
          type: path
      outputs:
        eval_output:
          type: path
      environment: azureml:AzureML-Minimal:1
      code:
        local_path: ./eval_src
      command: >-
        python eval.py 
        --scoring_result ${{inputs.scoring_result}}
        --eval_output ${{outputs.eval_output}}

    inputs:
      scoring_result: ${{jobs.score-job.outputs.score_output}}
    outputs:
      eval_output: ${{outputs.pipeline_job_evaluation_report}}

```
